apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
    - name: red-container
      image: busybox:1.28
  initContainers:
    - name: sleep-container
      image: busybox
      command:
        - sh
        - -c
        - sleep 20