apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-2
spec:
  containers:
    - name: simple-webapp
      image: kodekloud/webapp-delayed-start
      env:
        - name: APP_START_DELAY
          value: "80"
      ports:
        - containerPort: 8080
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
      livenessProbe:
        httpGet:
          path: /live
          port: 8080
        initialDelaySeconds: 80
        periodSeconds: 1